# Generated by Django 2.1.5 on 2019-01-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(default=True, upload_to='Temp/'),
            preserve_default=False,
        ),
    ]
